// @generated
// This file was automatically generated and should not be edited.
// @see scripts/index-components.ts

export const components: Record<string, { path: string; classes: string[] }> =
  Object.freeze({
    Accordion: {
      path: "carbon-components-svelte/src/Accordion/Accordion.svelte",
      classes: [
        ".bx--accordion",
        ".bx--accordion--start",
        ".bx--accordion--end",
        ".bx--accordion--sm",
        ".bx--accordion--xl",
        ".bx--skeleton",
        ".bx--accordion__item",
        ".bx--accordion__item--active",
        ".bx--accordion__heading",
        ".bx--accordion__arrow",
        ".bx--accordion__title",
        ".bx--accordion__content",
      ],
    },
    AccordionItem: {
      path: "carbon-components-svelte/src/Accordion/AccordionItem.svelte",
      classes: [
        ".bx--accordion__item",
        ".bx--accordion__item--active",
        ".bx--accordion__item--disabled",
        ".bx--accordion__item--expanding",
        ".bx--accordion__item--collapsing",
        ".bx--accordion__heading",
        ".bx--accordion__arrow",
        ".bx--accordion__title",
        ".bx--accordion__content",
      ],
    },
    AccordionSkeleton: {
      path: "carbon-components-svelte/src/Accordion/AccordionSkeleton.svelte",
      classes: [
        ".bx--skeleton",
        ".bx--accordion",
        ".bx--accordion--start",
        ".bx--accordion--end",
        ".bx--accordion--sm",
        ".bx--accordion--xl",
        ".bx--accordion__item",
        ".bx--accordion__item--active",
        ".bx--accordion__heading",
        ".bx--accordion__arrow",
        ".bx--accordion__title",
        ".bx--accordion__content",
        ".bx--skeleton__text",
        ".bx--skeleton__heading",
      ],
    },
    AspectRatio: {
      path: "carbon-components-svelte/src/AspectRatio/AspectRatio.svelte",
      classes: [
        ".bx--aspect-ratio",
        ".bx--aspect-ratio--2x1",
        ".bx--aspect-ratio--2x3",
        ".bx--aspect-ratio--16x9",
        ".bx--aspect-ratio--4x3",
        ".bx--aspect-ratio--1x1",
        ".bx--aspect-ratio--3x4",
        ".bx--aspect-ratio--3x2",
        ".bx--aspect-ratio--9x16",
        ".bx--aspect-ratio--1x2",
        ".bx--aspect-ratio--object",
      ],
    },
    Breadcrumb: {
      path: "carbon-components-svelte/src/Breadcrumb/Breadcrumb.svelte",
      classes: [
        ".bx--breadcrumb",
        ".bx--breadcrumb--no-trailing-slash",
        ".bx--skeleton",
        ".bx--breadcrumb-item",
        ".bx--link",
      ],
    },
    BreadcrumbItem: {
      path: "carbon-components-svelte/src/Breadcrumb/BreadcrumbItem.svelte",
      classes: [
        ".bx--breadcrumb-item",
        ".bx--breadcrumb-item--current",
        ".bx--link",
        ".bx--link--disabled",
        ".bx--link--inline",
        ".bx--link--visited",
        ".bx--link__icon",
        ".bx--link--sm",
        ".bx--link--lg",
      ],
    },
    BreadcrumbSkeleton: {
      path: "carbon-components-svelte/src/Breadcrumb/BreadcrumbSkeleton.svelte",
      classes: [
        ".bx--skeleton",
        ".bx--breadcrumb",
        ".bx--breadcrumb--no-trailing-slash",
        ".bx--breadcrumb-item",
        ".bx--link",
      ],
    },
    Breakpoint: {
      path: "carbon-components-svelte/src/Breakpoint/Breakpoint.svelte",
      classes: [],
    },
    breakpointObserver: {
      path: "carbon-components-svelte/src/Breakpoint/breakpointObserver.js",
      classes: [],
    },
    breakpoints: {
      path: "carbon-components-svelte/src/Breakpoint/breakpoints.js",
      classes: [],
    },
    Button: {
      path: "carbon-components-svelte/src/Button/Button.svelte",
      classes: [
        ".bx--assistive-text",
        ".bx--btn__icon",
        ".bx--btn",
        ".bx--btn--expressive",
        ".bx--btn--sm",
        ".bx--btn--md",
        ".bx--btn--field",
        ".bx--btn--lg",
        ".bx--btn--xl",
        ".bx--btn--",
        ".bx--btn--disabled",
        ".bx--btn--icon-only",
        ".bx--tooltip__trigger",
        ".bx--tooltip--a11y",
        ".bx--btn--icon-only--",
        ".bx--tooltip--align-",
        ".bx--btn--selected",
        ".bx--skeleton",
      ],
    },
    ButtonSet: {
      path: "carbon-components-svelte/src/Button/ButtonSet.svelte",
      classes: [".bx--btn-set", ".bx--btn-set--stacked"],
    },
    ButtonSkeleton: {
      path: "carbon-components-svelte/src/Button/ButtonSkeleton.svelte",
      classes: [
        ".bx--skeleton",
        ".bx--btn",
        ".bx--btn--field",
        ".bx--btn--sm",
        ".bx--btn--lg",
        ".bx--btn--xl",
      ],
    },
    Checkbox: {
      path: "carbon-components-svelte/src/Checkbox/Checkbox.svelte",
      classes: [
        ".bx--form-item",
        ".bx--checkbox-wrapper",
        ".bx--checkbox-wrapper--readonly",
        ".bx--checkbox",
        ".bx--checkbox-label",
        ".bx--checkbox-label-text",
        ".bx--visually-hidden",
        ".bx--form__helper-text",
        ".bx--form__helper-text--disabled",
        ".bx--skeleton",
      ],
    },
    CheckboxSkeleton: {
      path: "carbon-components-svelte/src/Checkbox/CheckboxSkeleton.svelte",
      classes: [
        ".bx--form-item",
        ".bx--checkbox-wrapper",
        ".bx--checkbox-label",
        ".bx--checkbox-label-text",
        ".bx--skeleton",
      ],
    },
    ClickableTile: {
      path: "carbon-components-svelte/src/Tile/ClickableTile.svelte",
      classes: [
        ".bx--tile",
        ".bx--tile--clickable",
        ".bx--tile--is-clicked",
        ".bx--tile--light",
        ".bx--link",
        ".bx--link--disabled",
        ".bx--link--inline",
        ".bx--link--visited",
        ".bx--link__icon",
        ".bx--link--sm",
        ".bx--link--lg",
      ],
    },
    CodeSnippet: {
      path: "carbon-components-svelte/src/CodeSnippet/CodeSnippet.svelte",
      classes: [
        ".bx--snippet",
        ".bx--snippet--expand",
        ".bx--snippet--light",
        ".bx--snippet--no-copy",
        ".bx--snippet--wraptext",
        ".bx--snippet--single",
        ".bx--snippet--inline",
        ".bx--snippet--multi",
        ".bx--copy",
        ".bx--btn--copy",
        ".bx--copy-btn--animating",
        ".bx--copy-btn--fade-in",
        ".bx--copy-btn--fade-out",
        ".bx--assistive-text",
        ".bx--copy-btn__feedback",
        ".bx--snippet--disabled",
        ".bx--snippet-container",
        ".bx--snippet-btn--expand",
        ".bx--snippet-btn--text",
        ".bx--icon-chevron--down",
        ".bx--snippet__icon",
        ".bx--skeleton",
        ".bx--copy-btn",
        ".bx--btn__icon",
        ".bx--btn",
        ".bx--btn--expressive",
        ".bx--btn--sm",
        ".bx--btn--md",
        ".bx--btn--field",
        ".bx--btn--lg",
        ".bx--btn--xl",
        ".bx--btn--",
        ".bx--btn--disabled",
        ".bx--btn--icon-only",
        ".bx--tooltip__trigger",
        ".bx--tooltip--a11y",
        ".bx--btn--icon-only--",
        ".bx--tooltip--align-",
        ".bx--btn--selected",
      ],
    },
    CodeSnippetSkeleton: {
      path: "carbon-components-svelte/src/CodeSnippet/CodeSnippetSkeleton.svelte",
      classes: [
        ".bx--skeleton",
        ".bx--snippet",
        ".bx--snippet--single",
        ".bx--snippet--multi",
        ".bx--snippet-container",
      ],
    },
    Column: {
      path: "carbon-components-svelte/src/Grid/Column.svelte",
      classes: [
        ".bx--col-",
        ".bx--offset-",
        ".bx--col",
        ".bx--no-gutter",
        ".bx--no-gutter--left",
        ".bx--no-gutter--right",
        ".bx--aspect-ratio bx--aspect-ratio--",
        ".bx--col-padding",
      ],
    },
    ComboBox: {
      path: "carbon-components-svelte/src/ComboBox/ComboBox.svelte",
      classes: [
        ".bx--list-box__wrapper",
        ".bx--label",
        ".bx--label--disabled",
        ".bx--visually-hidden",
        ".bx--combo-box",
        ".bx--list-box--up",
        ".bx--combo-box--warning",
        ".bx--list-box__field",
        ".bx--text-input",
        ".bx--text-input--light",
        ".bx--text-input--empty",
        ".bx--list-box__invalid-icon",
        ".bx--list-box__invalid-icon--warning",
        ".bx--list-box__menu-item__selected-icon",
        ".bx--form__helper-text",
        ".bx--form__helper-text--disabled",
        ".bx--list-box",
        ".bx--list-box--sm",
        ".bx--list-box--xl",
        ".bx--list-box--inline",
        ".bx--list-box--disabled",
        ".bx--list-box--expanded",
        ".bx--list-box--light",
        ".bx--list-box--warning",
        ".bx--form-requirement",
        ".bx--tag",
        ".bx--tag--filter",
        ".bx--tag--high-contrast",
        ".bx--tag--disabled",
        ".bx--tag__label",
        ".bx--tag__close-icon",
        ".bx--list-box__selection",
        ".bx--list-box__selection--multi",
        ".bx--list-box__menu-icon",
        ".bx--list-box__menu-icon--open",
        ".bx--list-box__menu",
        ".bx--list-box__menu-item",
        ".bx--list-box__menu-item--active",
        ".bx--list-box__menu-item--highlighted",
        ".bx--list-box__menu-item__option",
      ],
    },
    ComposedModal: {
      path: "carbon-components-svelte/src/ComposedModal/ComposedModal.svelte",
      classes: [
        ".bx--modal",
        ".is-visible",
        ".bx--modal--danger",
        ".bx--modal-container",
        ".bx--modal-container--xs",
        ".bx--modal-container--sm",
        ".bx--modal-container--lg",
      ],
    },
    Content: {
      path: "carbon-components-svelte/src/UIShell/Content.svelte",
      classes: [".bx--content"],
    },
    ContentSwitcher: {
      path: "carbon-components-svelte/src/ContentSwitcher/ContentSwitcher.svelte",
      classes: [
        ".bx--content-switcher",
        ".bx--content-switcher--sm",
        ".bx--content-switcher--xl",
      ],
    },
    ContextMenu: {
      path: "carbon-components-svelte/src/ContextMenu/ContextMenu.svelte",
      classes: [
        ".bx--menu",
        ".bx--menu--open",
        ".bx--menu--invisible",
        ".bx--menu--root",
      ],
    },
    ContextMenuDivider: {
      path: "carbon-components-svelte/src/ContextMenu/ContextMenuDivider.svelte",
      classes: [".bx--menu-divider"],
    },
    ContextMenuGroup: {
      path: "carbon-components-svelte/src/ContextMenu/ContextMenuGroup.svelte",
      classes: [],
    },
    ContextMenuOption: {
      path: "carbon-components-svelte/src/ContextMenu/ContextMenuOption.svelte",
      classes: [
        ".bx--menu-option",
        ".bx--menu-option--disabled",
        ".bx--menu-option--active",
        ".bx--menu-option--danger",
        ".bx--menu",
        ".bx--menu-option__content",
        ".bx--menu-option__content--disabled",
        ".bx--menu-option__icon",
        ".bx--menu-option__label",
        ".bx--menu-option__info",
        ".bx--menu--open",
        ".bx--menu--invisible",
        ".bx--menu--root",
      ],
    },
    ContextMenuRadioGroup: {
      path: "carbon-components-svelte/src/ContextMenu/ContextMenuRadioGroup.svelte",
      classes: [],
    },
    CopyButton: {
      path: "carbon-components-svelte/src/CopyButton/CopyButton.svelte",
      classes: [
        ".bx--copy-btn",
        ".bx--copy",
        ".bx--copy-btn--animating",
        ".bx--copy-btn--fade-in",
        ".bx--copy-btn--fade-out",
        ".bx--snippet__icon",
        ".bx--assistive-text",
        ".bx--copy-btn__feedback",
      ],
    },
    DataTable: {
      path: "carbon-components-svelte/src/DataTable/DataTable.svelte",
      classes: [
        ".bx--data-table-header",
        ".bx--data-table-header__title",
        ".bx--data-table-header__description",
        ".bx--table-expand",
        ".bx--table-expand__button",
        ".bx--table-expand__svg",
        ".bx--table-column-checkbox",
        ".bx--data-table--selected",
        ".bx--expandable-row",
        ".bx--parent-row",
        ".bx--expandable-row--hover",
        ".bx--table-column-radio",
        ".bx--table-column-menu",
        ".bx--child-row-inner-container",
        ".bx--data-table-container",
        ".bx--data-table-container--static",
        ".bx--data-table--max-width",
        ".bx--data-table_inner-container",
        ".bx--data-table",
        ".bx--data-table--compact",
        ".bx--data-table--short",
        ".bx--data-table--tall",
        ".bx--data-table--md",
        ".bx--data-table--sort",
        ".bx--data-table--zebra",
        ".bx--data-table--static",
        ".bx--data-table--sticky-header",
        ".bx--checkbox--inline",
        ".bx--checkbox",
        ".bx--checkbox-label",
        ".bx--table-sort",
        ".bx--table-sort--active",
        ".bx--table-sort--ascending",
        ".bx--table-header-label",
        ".bx--table-sort__icon",
        ".bx--table-sort__icon-unsorted",
        ".bx--radio-button-wrapper",
        ".bx--radio-button-wrapper--label-left",
        ".bx--radio-button",
        ".bx--radio-button__label",
        ".bx--radio-button__appearance",
        ".bx--visually-hidden",
      ],
    },
    DataTableSkeleton: {
      path: "carbon-components-svelte/src/DataTable/DataTableSkeleton.svelte",
      classes: [
        ".bx--skeleton",
        ".bx--data-table-container",
        ".bx--data-table-header",
        ".bx--data-table-header__title",
        ".bx--data-table-header__description",
        ".bx--table-toolbar",
        ".bx--toolbar-content",
        ".bx--btn",
        ".bx--btn--sm",
        ".bx--data-table",
        ".bx--data-table--compact",
        ".bx--data-table--short",
        ".bx--data-table--tall",
        ".bx--data-table--zebra",
      ],
    },
    DatePicker: {
      path: "carbon-components-svelte/src/DatePicker/DatePicker.svelte",
      classes: [
        ".bx--form-item",
        ".bx--date-picker",
        ".bx--date-picker--short",
        ".bx--date-picker--light",
        ".bx--date-picker--simple",
        ".bx--date-picker--single",
        ".bx--date-picker--range",
        ".bx--date-picker--nolabel",
      ],
    },
    DatePickerInput: {
      path: "carbon-components-svelte/src/DatePicker/DatePickerInput.svelte",
      classes: [
        ".bx--date-picker-container",
        ".bx--date-picker--nolabel",
        ".bx--label",
        ".bx--visually-hidden",
        ".bx--label--disabled",
        ".bx--date-picker-input__wrapper",
        ".bx--date-picker-input__wrapper--invalid",
        ".bx--date-picker-input__wrapper--warn",
        ".bx--date-picker__input",
        ".bx--date-picker__input--invalid",
        ".bx--date-picker__input--sm",
        ".bx--date-picker__input--xl",
        ".bx--date-picker__icon",
        ".bx--date-picker__icon--invalid",
        ".bx--date-picker__icon--warn",
        ".bx--form-requirement",
        ".bx--form__helper-text",
        ".bx--form__helper-text--disabled",
      ],
    },
    DatePickerSkeleton: {
      path: "carbon-components-svelte/src/DatePicker/DatePickerSkeleton.svelte",
      classes: [
        ".bx--form-item",
        ".bx--date-picker",
        ".bx--skeleton",
        ".bx--date-picker--range",
        ".bx--date-picker--short",
        ".bx--date-picker--simple",
        ".bx--date-picker-container",
        ".bx--label",
        ".bx--date-picker__input",
      ],
    },
    Dropdown: {
      path: "carbon-components-svelte/src/Dropdown/Dropdown.svelte",
      classes: [
        ".bx--dropdown__wrapper",
        ".bx--list-box__wrapper",
        ".bx--dropdown__wrapper--inline",
        ".bx--list-box__wrapper--inline",
        ".bx--dropdown__wrapper--inline--invalid",
        ".bx--label",
        ".bx--label--disabled",
        ".bx--visually-hidden",
        ".bx--dropdown",
        ".bx--list-box--up",
        ".bx--dropdown--invalid",
        ".bx--dropdown--warning",
        ".bx--dropdown--open",
        ".bx--dropdown--sm",
        ".bx--dropdown--xl",
        ".bx--dropdown--inline",
        ".bx--dropdown--disabled",
        ".bx--dropdown--light",
        ".bx--list-box__invalid-icon",
        ".bx--list-box__invalid-icon--warning",
        ".bx--list-box__field",
        ".bx--list-box__label",
        ".bx--form__helper-text",
        ".bx--form__helper-text--disabled",
        ".bx--list-box",
        ".bx--list-box--sm",
        ".bx--list-box--xl",
        ".bx--list-box--inline",
        ".bx--list-box--disabled",
        ".bx--list-box--expanded",
        ".bx--list-box--light",
        ".bx--list-box--warning",
        ".bx--form-requirement",
        ".bx--list-box__menu-icon",
        ".bx--list-box__menu-icon--open",
        ".bx--list-box__menu",
        ".bx--list-box__menu-item",
        ".bx--list-box__menu-item--active",
        ".bx--list-box__menu-item--highlighted",
        ".bx--list-box__menu-item__option",
      ],
    },
    DropdownSkeleton: {
      path: "carbon-components-svelte/src/Dropdown/DropdownSkeleton.svelte",
      classes: [
        ".bx--skeleton",
        ".bx--dropdown-v2",
        ".bx--list-box",
        ".bx--form-item",
        ".bx--list-box--inline",
        ".bx--list-box__field",
        ".bx--list-box__label",
      ],
    },
    ExpandableTile: {
      path: "carbon-components-svelte/src/Tile/ExpandableTile.svelte",
      classes: [
        ".bx--tile",
        ".bx--tile--expandable",
        ".bx--tile--is-expanded",
        ".bx--tile--light",
        ".bx--tile-content",
        ".bx--tile-content__above-the-fold",
        ".bx--tile__chevron",
        ".bx--tile-content__below-the-fold",
      ],
    },
    Filename: {
      path: "carbon-components-svelte/src/FileUploader/Filename.svelte",
      classes: [
        ".bx--file-invalid",
        ".bx--file-close",
        ".bx--file-complete",
        ".bx--loading-overlay",
        ".bx--loading-overlay--stop",
        ".bx--loading",
        ".bx--loading--small",
        ".bx--loading--stop",
        ".bx--loading__svg",
        ".bx--loading__background",
        ".bx--loading__stroke",
      ],
    },
    FileUploader: {
      path: "carbon-components-svelte/src/FileUploader/FileUploader.svelte",
      classes: [
        ".bx--form-item",
        ".bx--file--label",
        ".bx--label-description--disabled",
        ".bx--label-description",
        ".bx--file-container",
        ".bx--file__selected-file",
        ".bx--file-filename",
        ".bx--file__state-container",
        ".bx--btn",
        ".bx--btn--disabled",
        ".bx--btn--primary",
        ".bx--btn--secondary",
        ".bx--btn--tertiary",
        ".bx--btn--ghost",
        ".bx--btn--danger",
        ".bx--btn--danger-tertiary",
        ".bx--btn--danger-ghost",
        ".bx--btn--sm",
        ".bx--btn--field",
        ".bx--btn--lg",
        ".bx--btn--xl",
        ".bx--visually-hidden",
        ".bx--file-invalid",
        ".bx--file-close",
        ".bx--file-complete",
      ],
    },
    FileUploaderButton: {
      path: "carbon-components-svelte/src/FileUploader/FileUploaderButton.svelte",
      classes: [
        ".bx--btn",
        ".bx--btn--disabled",
        ".bx--btn--primary",
        ".bx--btn--secondary",
        ".bx--btn--tertiary",
        ".bx--btn--ghost",
        ".bx--btn--danger",
        ".bx--btn--danger-tertiary",
        ".bx--btn--danger-ghost",
        ".bx--btn--sm",
        ".bx--btn--field",
        ".bx--btn--lg",
        ".bx--btn--xl",
        ".bx--visually-hidden",
      ],
    },
    FileUploaderDropContainer: {
      path: "carbon-components-svelte/src/FileUploader/FileUploaderDropContainer.svelte",
      classes: [
        ".bx--file",
        ".bx--file-browse-btn",
        ".bx--file-browse-btn--disabled",
        ".bx--file__drop-container",
        ".bx--file__drop-container--drag-over",
        ".bx--file-input",
      ],
    },
    FileUploaderItem: {
      path: "carbon-components-svelte/src/FileUploader/FileUploaderItem.svelte",
      classes: [
        ".bx--file__selected-file",
        ".bx--file__selected-file--invalid",
        ".bx--file__selected-file--md",
        ".bx--file__selected-file--sm",
        ".bx--file-filename",
        ".bx--file__state-container",
        ".bx--form-requirement",
        ".bx--form-requirement__title",
        ".bx--form-requirement__supplement",
        ".bx--file-invalid",
        ".bx--file-close",
        ".bx--file-complete",
      ],
    },
    FileUploaderSkeleton: {
      path: "carbon-components-svelte/src/FileUploader/FileUploaderSkeleton.svelte",
      classes: [
        ".bx--form-item",
        ".bx--label-description",
        ".bx--skeleton__text",
        ".bx--skeleton__heading",
        ".bx--skeleton",
        ".bx--btn",
        ".bx--btn--field",
        ".bx--btn--sm",
        ".bx--btn--lg",
        ".bx--btn--xl",
      ],
    },
    filterTreeNodes: {
      path: "carbon-components-svelte/src/utils/filterTreeNodes.js",
      classes: [],
    },
    FluidForm: {
      path: "carbon-components-svelte/src/FluidForm/FluidForm.svelte",
      classes: [".bx--form--fluid", ".bx--form"],
    },
    Form: {
      path: "carbon-components-svelte/src/Form/Form.svelte",
      classes: [".bx--form"],
    },
    FormGroup: {
      path: "carbon-components-svelte/src/FormGroup/FormGroup.svelte",
      classes: [
        ".bx--fieldset",
        ".bx--fieldset--no-margin",
        ".bx--label",
        ".bx--form__requirement",
      ],
    },
    FormItem: {
      path: "carbon-components-svelte/src/FormItem/FormItem.svelte",
      classes: [".bx--form-item"],
    },
    FormLabel: {
      path: "carbon-components-svelte/src/FormLabel/FormLabel.svelte",
      classes: [".bx--label"],
    },
    Grid: {
      path: "carbon-components-svelte/src/Grid/Grid.svelte",
      classes: [
        ".bx--grid",
        ".bx--grid--condensed",
        ".bx--grid--narrow",
        ".bx--grid--full-width",
        ".bx--no-gutter",
        ".bx--no-gutter--left",
        ".bx--no-gutter--right",
        ".bx--row-padding",
      ],
    },
    Header: {
      path: "carbon-components-svelte/src/UIShell/Header.svelte",
      classes: [
        ".bx--header",
        ".bx--header__name",
        ".bx--header__name--prefix",
        ".bx--header__action",
        ".bx--header__menu-trigger",
        ".bx--header__menu-toggle",
      ],
    },
    HeaderAction: {
      path: "carbon-components-svelte/src/UIShell/HeaderAction.svelte",
      classes: [
        ".bx--header__action",
        ".bx--header__action--active",
        ".bx--header__action--text",
        ".bx--assistive-text",
        ".bx--header__action-text",
        ".bx--header-panel",
        ".bx--header-panel--expanded",
        ".bx--btn bx--btn--primary",
        ".bx--tooltip__trigger bx--tooltip--a11y",
        ".bx--btn--icon-only bx--btn--icon-only--bottom",
        ".bx--tooltip--align-",
      ],
    },
    HeaderActionLink: {
      path: "carbon-components-svelte/src/UIShell/HeaderActionLink.svelte",
      classes: [".bx--header__action", ".bx--header__action--active"],
    },
    HeaderGlobalAction: {
      path: "carbon-components-svelte/src/UIShell/HeaderGlobalAction.svelte",
      classes: [
        ".bx--header__action",
        ".bx--header__action--active",
        ".bx--assistive-text",
        ".bx--btn__icon",
        ".bx--btn",
        ".bx--btn--expressive",
        ".bx--btn--sm",
        ".bx--btn--md",
        ".bx--btn--field",
        ".bx--btn--lg",
        ".bx--btn--xl",
        ".bx--btn--",
        ".bx--btn--disabled",
        ".bx--btn--icon-only",
        ".bx--tooltip__trigger",
        ".bx--tooltip--a11y",
        ".bx--btn--icon-only--",
        ".bx--tooltip--align-",
        ".bx--btn--selected",
        ".bx--skeleton",
      ],
    },
    HeaderNav: {
      path: "carbon-components-svelte/src/UIShell/HeaderNav.svelte",
      classes: [".bx--header__nav", ".bx--header__menu-bar"],
    },
    HeaderNavItem: {
      path: "carbon-components-svelte/src/UIShell/HeaderNavItem.svelte",
      classes: [".bx--header__menu-item", ".bx--text-truncate--end"],
    },
    HeaderNavMenu: {
      path: "carbon-components-svelte/src/UIShell/HeaderNavMenu.svelte",
      classes: [
        ".bx--header__submenu",
        ".bx--header__submenu--current",
        ".bx--header__menu-item",
        ".bx--header__menu-title",
        ".bx--header__menu-arrow",
        ".bx--header__menu",
      ],
    },
    HeaderPanelDivider: {
      path: "carbon-components-svelte/src/UIShell/HeaderPanelDivider.svelte",
      classes: [".bx--header-panel-divider", ".bx--switcher__item--divider"],
    },
    HeaderPanelLink: {
      path: "carbon-components-svelte/src/UIShell/HeaderPanelLink.svelte",
      classes: [".bx--switcher__item", ".bx--switcher__item-link"],
    },
    HeaderPanelLinks: {
      path: "carbon-components-svelte/src/UIShell/HeaderPanelLinks.svelte",
      classes: [".bx--switcher__item"],
    },
    HeaderSearch: {
      path: "carbon-components-svelte/src/UIShell/HeaderSearch.svelte",
      classes: [
        ".bx--header__search",
        ".bx--header__search--active",
        ".bx--header__search-label",
        ".bx--header__search-menu",
        ".bx--header-search-button",
        ".bx--header__action",
        ".bx--header-search-button--disabled",
        ".bx--header__search-input",
        ".bx--header-search-button--hidden",
        ".bx--header-search-menu",
        ".bx--header-search-menu-item",
        ".bx--header-search-menu-item--selected",
        ".bx--header-search-menu-description",
        ".bx--header__search:not(.bx--header__search--active)",
        ".bx--header__search.bx--header__search--active",
        ".bx--header__search-input:not(.bx--header__search--active)",
        ".bx--header-search-button:hover",
        ".bx--header-search-menu-item:hover",
      ],
    },
    HeaderUtilities: {
      path: "carbon-components-svelte/src/UIShell/HeaderUtilities.svelte",
      classes: [".bx--header__global"],
    },
    ImageLoader: {
      path: "carbon-components-svelte/src/ImageLoader/ImageLoader.svelte",
      classes: [
        ".bx--aspect-ratio",
        ".bx--aspect-ratio--2x1",
        ".bx--aspect-ratio--2x3",
        ".bx--aspect-ratio--16x9",
        ".bx--aspect-ratio--4x3",
        ".bx--aspect-ratio--1x1",
        ".bx--aspect-ratio--3x4",
        ".bx--aspect-ratio--3x2",
        ".bx--aspect-ratio--9x16",
        ".bx--aspect-ratio--1x2",
        ".bx--aspect-ratio--object",
      ],
    },
    InlineLoading: {
      path: "carbon-components-svelte/src/InlineLoading/InlineLoading.svelte",
      classes: [
        ".bx--inline-loading",
        ".bx--inline-loading__animation",
        ".bx--inline-loading--error",
        ".bx--inline-loading__checkmark-container",
        ".bx--inline-loading__text",
        ".bx--loading-overlay",
        ".bx--loading-overlay--stop",
        ".bx--loading",
        ".bx--loading--small",
        ".bx--loading--stop",
        ".bx--loading__svg",
        ".bx--loading__background",
        ".bx--loading__stroke",
      ],
    },
    InlineNotification: {
      path: "carbon-components-svelte/src/Notification/InlineNotification.svelte",
      classes: [
        ".bx--inline-notification",
        ".bx--inline-notification--low-contrast",
        ".bx--inline-notification--hide-close-button",
        ".bx--inline-notification--error",
        ".bx--inline-notification--info",
        ".bx--inline-notification--info-square",
        ".bx--inline-notification--success",
        ".bx--inline-notification--warning",
        ".bx--inline-notification--warning-alt",
        ".bx--inline-notification__details",
        ".bx--inline-notification__text-wrapper",
        ".bx--inline-notification__title",
        ".bx--inline-notification__subtitle",
        ".bx--toast-notification__icon",
        ".bx--inline-notification__icon",
        ".bx--toast-notification__close-button",
        ".bx--inline-notification__close-button",
        ".bx--toast-notification__close-icon",
        ".bx--inline-notification__close-icon",
      ],
    },
    Link: {
      path: "carbon-components-svelte/src/Link/Link.svelte",
      classes: [
        ".bx--link",
        ".bx--link--disabled",
        ".bx--link--inline",
        ".bx--link--visited",
        ".bx--link__icon",
        ".bx--link--sm",
        ".bx--link--lg",
      ],
    },
    ListBox: {
      path: "carbon-components-svelte/src/ListBox/ListBox.svelte",
      classes: [
        ".bx--list-box",
        ".bx--list-box--sm",
        ".bx--list-box--xl",
        ".bx--list-box--inline",
        ".bx--list-box--disabled",
        ".bx--list-box--expanded",
        ".bx--list-box--light",
        ".bx--list-box--warning",
        ".bx--form-requirement",
      ],
    },
    ListBoxField: {
      path: "carbon-components-svelte/src/ListBox/ListBoxField.svelte",
      classes: [".bx--list-box__field"],
    },
    ListBoxMenu: {
      path: "carbon-components-svelte/src/ListBox/ListBoxMenu.svelte",
      classes: [".bx--list-box__menu"],
    },
    ListBoxMenuIcon: {
      path: "carbon-components-svelte/src/ListBox/ListBoxMenuIcon.svelte",
      classes: [".bx--list-box__menu-icon", ".bx--list-box__menu-icon--open"],
    },
    ListBoxMenuItem: {
      path: "carbon-components-svelte/src/ListBox/ListBoxMenuItem.svelte",
      classes: [
        ".bx--list-box__menu-item",
        ".bx--list-box__menu-item--active",
        ".bx--list-box__menu-item--highlighted",
        ".bx--list-box__menu-item__option",
      ],
    },
    ListBoxSelection: {
      path: "carbon-components-svelte/src/ListBox/ListBoxSelection.svelte",
      classes: [
        ".bx--tag",
        ".bx--tag--filter",
        ".bx--tag--high-contrast",
        ".bx--tag--disabled",
        ".bx--tag__label",
        ".bx--tag__close-icon",
        ".bx--list-box__selection",
        ".bx--list-box__selection--multi",
      ],
    },
    ListItem: {
      path: "carbon-components-svelte/src/ListItem/ListItem.svelte",
      classes: [".bx--list__item"],
    },
    Loading: {
      path: "carbon-components-svelte/src/Loading/Loading.svelte",
      classes: [
        ".bx--loading-overlay",
        ".bx--loading-overlay--stop",
        ".bx--loading",
        ".bx--loading--small",
        ".bx--loading--stop",
        ".bx--loading__svg",
        ".bx--loading__background",
        ".bx--loading__stroke",
      ],
    },
    LocalStorage: {
      path: "carbon-components-svelte/src/LocalStorage/LocalStorage.svelte",
      classes: [],
    },
    Modal: {
      path: "carbon-components-svelte/src/Modal/Modal.svelte",
      classes: [
        ".bx--modal",
        ".bx--modal-tall",
        ".is-visible",
        ".bx--modal--danger",
        ".bx--modal-container",
        ".bx--modal-container--xs",
        ".bx--modal-container--sm",
        ".bx--modal-container--lg",
        ".bx--modal-header",
        ".bx--modal-close",
        ".bx--modal-close__icon",
        ".bx--modal-header__label",
        ".bx--modal-header__heading",
        ".bx--modal-content",
        ".bx--modal-content--with-form",
        ".bx--modal-scroll-content",
        ".bx--modal-content--overflow-indicator",
        ".bx--modal-footer",
        ".bx--modal-footer--three-button",
        ".bx--modal-header__label--modal-",
        ".bx--modal-header__heading--modal-",
        ".bx--modal-body--",
        ".bx--assistive-text",
        ".bx--btn__icon",
        ".bx--btn",
        ".bx--btn--expressive",
        ".bx--btn--sm",
        ".bx--btn--md",
        ".bx--btn--field",
        ".bx--btn--lg",
        ".bx--btn--xl",
        ".bx--btn--",
        ".bx--btn--disabled",
        ".bx--btn--icon-only",
        ".bx--tooltip__trigger",
        ".bx--tooltip--a11y",
        ".bx--btn--icon-only--",
        ".bx--tooltip--align-",
        ".bx--btn--selected",
      ],
    },
    ModalBody: {
      path: "carbon-components-svelte/src/ComposedModal/ModalBody.svelte",
      classes: [
        ".bx--modal-content",
        ".bx--modal-content--with-form",
        ".bx--modal-scroll-content",
        ".bx--modal-content--overflow-indicator",
      ],
    },
    ModalFooter: {
      path: "carbon-components-svelte/src/ComposedModal/ModalFooter.svelte",
      classes: [
        ".bx--modal-footer",
        ".bx--modal-footer--three-button",
        ".bx--assistive-text",
        ".bx--btn__icon",
        ".bx--btn",
        ".bx--btn--expressive",
        ".bx--btn--sm",
        ".bx--btn--md",
        ".bx--btn--field",
        ".bx--btn--lg",
        ".bx--btn--xl",
        ".bx--btn--",
        ".bx--btn--disabled",
        ".bx--btn--icon-only",
        ".bx--tooltip__trigger",
        ".bx--tooltip--a11y",
        ".bx--btn--icon-only--",
        ".bx--tooltip--align-",
        ".bx--btn--selected",
        ".bx--skeleton",
      ],
    },
    ModalHeader: {
      path: "carbon-components-svelte/src/ComposedModal/ModalHeader.svelte",
      classes: [
        ".bx--modal-header",
        ".bx--modal-header__label",
        ".bx--type-delta",
        ".bx--modal-header__heading",
        ".bx--type-beta",
        ".bx--modal-close",
        ".bx--modal-close__icon",
      ],
    },
    MultiSelect: {
      path: "carbon-components-svelte/src/MultiSelect/MultiSelect.svelte",
      classes: [
        ".bx--multi-select__wrapper",
        ".bx--list-box__wrapper",
        ".bx--multi-select__wrapper--inline",
        ".bx--list-box__wrapper--inline",
        ".bx--multi-select__wrapper--inline--invalid",
        ".bx--label",
        ".bx--label--disabled",
        ".bx--visually-hidden",
        ".bx--multi-select",
        ".bx--list-box--up",
        ".bx--combo-box",
        ".bx--multi-select--filterable",
        ".bx--multi-select--invalid",
        ".bx--multi-select--inline",
        ".bx--multi-select--selected",
        ".bx--list-box__invalid-icon",
        ".bx--list-box__invalid-icon--warning",
        ".bx--list-box__field",
        ".bx--text-input",
        ".bx--text-input--empty",
        ".bx--text-input--light",
        ".bx--list-box__label",
        ".bx--form__helper-text",
        ".bx--form__helper-text--disabled",
        ".bx--list-box",
        ".bx--list-box--sm",
        ".bx--list-box--xl",
        ".bx--list-box--inline",
        ".bx--list-box--disabled",
        ".bx--list-box--expanded",
        ".bx--list-box--light",
        ".bx--list-box--warning",
        ".bx--form-requirement",
        ".bx--tag",
        ".bx--tag--filter",
        ".bx--tag--high-contrast",
        ".bx--tag--disabled",
        ".bx--tag__label",
        ".bx--tag__close-icon",
        ".bx--list-box__selection",
        ".bx--list-box__selection--multi",
        ".bx--list-box__menu-icon",
        ".bx--list-box__menu-icon--open",
        ".bx--list-box__menu",
        ".bx--list-box__menu-item",
        ".bx--list-box__menu-item--active",
        ".bx--list-box__menu-item--highlighted",
        ".bx--list-box__menu-item__option",
        ".bx--form-item",
        ".bx--checkbox-wrapper",
        ".bx--checkbox-wrapper--readonly",
        ".bx--checkbox",
        ".bx--checkbox-label",
        ".bx--checkbox-label-text",
      ],
    },
    NotificationActionButton: {
      path: "carbon-components-svelte/src/Notification/NotificationActionButton.svelte",
      classes: [
        ".bx--inline-notification__action-button",
        ".bx--assistive-text",
        ".bx--btn__icon",
        ".bx--btn",
        ".bx--btn--expressive",
        ".bx--btn--sm",
        ".bx--btn--md",
        ".bx--btn--field",
        ".bx--btn--lg",
        ".bx--btn--xl",
        ".bx--btn--",
        ".bx--btn--disabled",
        ".bx--btn--icon-only",
        ".bx--tooltip__trigger",
        ".bx--tooltip--a11y",
        ".bx--btn--icon-only--",
        ".bx--tooltip--align-",
        ".bx--btn--selected",
        ".bx--skeleton",
      ],
    },
    NotificationButton: {
      path: "carbon-components-svelte/src/Notification/NotificationButton.svelte",
      classes: [
        ".bx--toast-notification__close-button",
        ".bx--inline-notification__close-button",
        ".bx--toast-notification__close-icon",
        ".bx--inline-notification__close-icon",
      ],
    },
    NotificationIcon: {
      path: "carbon-components-svelte/src/Notification/NotificationIcon.svelte",
      classes: [
        ".bx--toast-notification__icon",
        ".bx--inline-notification__icon",
      ],
    },
    NotificationQueue: {
      path: "carbon-components-svelte/src/Notification/NotificationQueue.svelte",
      classes: [
        ".bx--toast-notification",
        ".bx--toast-notification--low-contrast",
        ".bx--toast-notification--error",
        ".bx--toast-notification--info",
        ".bx--toast-notification--info-square",
        ".bx--toast-notification--success",
        ".bx--toast-notification--warning",
        ".bx--toast-notification--warning-alt",
        ".bx--toast-notification__details",
        ".bx--toast-notification__title",
        ".bx--toast-notification__subtitle",
        ".bx--toast-notification__caption",
      ],
    },
    NumberInput: {
      path: "carbon-components-svelte/src/NumberInput/NumberInput.svelte",
      classes: [
        ".bx--form-item",
        ".bx--number",
        ".bx--number--helpertext",
        ".bx--number--readonly",
        ".bx--number--light",
        ".bx--number--nolabel",
        ".bx--number--nosteppers",
        ".bx--number--sm",
        ".bx--number--xl",
        ".bx--label",
        ".bx--label--disabled",
        ".bx--visually-hidden",
        ".bx--number__input-wrapper",
        ".bx--number__input-wrapper--warning",
        ".bx--text-input__readonly-icon",
        ".bx--number__invalid",
        ".bx--number__invalid--warning",
        ".bx--number__controls",
        ".bx--number__control-btn",
        ".down-icon",
        ".bx--number__rule-divider",
        ".up-icon",
        ".bx--form__helper-text",
        ".bx--form__helper-text--disabled",
        ".bx--form-requirement",
      ],
    },
    NumberInputSkeleton: {
      path: "carbon-components-svelte/src/NumberInput/NumberInputSkeleton.svelte",
      classes: [".bx--form-item", ".bx--label", ".bx--skeleton", ".bx--number"],
    },
    OrderedList: {
      path: "carbon-components-svelte/src/OrderedList/OrderedList.svelte",
      classes: [
        ".bx--list--ordered",
        ".bx--list--ordered--native",
        ".bx--list--nested",
        ".bx--list--expressive",
      ],
    },
    OutboundLink: {
      path: "carbon-components-svelte/src/Link/OutboundLink.svelte",
      classes: [
        ".bx--link",
        ".bx--link--disabled",
        ".bx--link--inline",
        ".bx--link--visited",
        ".bx--link__icon",
        ".bx--link--sm",
        ".bx--link--lg",
      ],
    },
    OverflowMenu: {
      path: "carbon-components-svelte/src/OverflowMenu/OverflowMenu.svelte",
      classes: [
        ".bx--overflow-menu",
        ".bx--overflow-menu--open",
        ".bx--overflow-menu--light",
        ".bx--overflow-menu--sm",
        ".bx--overflow-menu--xl",
        ".bx--overflow-menu__icon",
        ".bx--overflow-menu-options",
        ".bx--overflow-menu--flip",
        ".bx--overflow-menu-options--open",
        ".bx--overflow-menu-options--light",
        ".bx--overflow-menu-options--sm",
        ".bx--overflow-menu-options--xl",
        ".bx--breadcrumb-menu-options",
      ],
    },
    OverflowMenuItem: {
      path: "carbon-components-svelte/src/OverflowMenu/OverflowMenuItem.svelte",
      classes: [
        ".bx--overflow-menu-options__option",
        ".bx--overflow-menu--divider",
        ".bx--overflow-menu-options__option--danger",
        ".bx--overflow-menu-options__option--disabled",
        ".bx--overflow-menu-options__option-content",
        ".bx--overflow-menu-options__btn",
      ],
    },
    Pagination: {
      path: "carbon-components-svelte/src/Pagination/Pagination.svelte",
      classes: [
        ".bx--pagination",
        ".bx--pagination__left",
        ".bx--pagination__text",
        ".bx--select__item-count",
        ".bx--pagination__right",
        ".bx--select__page-number",
        ".bx--pagination__button",
        ".bx--pagination__button--backward",
        ".bx--pagination__button--no-index",
        ".bx--pagination__button--forward",
        ".bx--form-item",
        ".bx--select",
        ".bx--select--inline",
        ".bx--select--light",
        ".bx--select--invalid",
        ".bx--select--disabled",
        ".bx--select--warning",
        ".bx--label",
        ".bx--visually-hidden",
        ".bx--label--disabled",
        ".bx--select-input--inline__wrapper",
        ".bx--select-input__wrapper",
        ".bx--select-input",
        ".bx--select-input--sm",
        ".bx--select-input--xl",
        ".bx--select__arrow",
        ".bx--select__invalid-icon",
        ".bx--form-requirement",
        ".bx--form__helper-text",
        ".bx--form__helper-text--disabled",
        ".bx--select__invalid-icon--warning",
        ".bx--select-option",
        ".bx--assistive-text",
        ".bx--btn__icon",
        ".bx--btn",
        ".bx--btn--expressive",
        ".bx--btn--sm",
        ".bx--btn--md",
        ".bx--btn--field",
        ".bx--btn--lg",
        ".bx--btn--xl",
        ".bx--btn--",
        ".bx--btn--disabled",
        ".bx--btn--icon-only",
        ".bx--tooltip__trigger",
        ".bx--tooltip--a11y",
        ".bx--btn--icon-only--",
        ".bx--tooltip--align-",
        ".bx--btn--selected",
        ".bx--skeleton",
      ],
    },
    PaginationNav: {
      path: "carbon-components-svelte/src/PaginationNav/PaginationNav.svelte",
      classes: [
        ".bx--pagination-nav",
        ".bx--pagination-nav__list",
        ".bx--pagination-nav__list-item",
        ".bx--pagination-nav__accessibility-label",
        ".bx--assistive-text",
        ".bx--btn__icon",
        ".bx--btn",
        ".bx--btn--expressive",
        ".bx--btn--sm",
        ".bx--btn--md",
        ".bx--btn--field",
        ".bx--btn--lg",
        ".bx--btn--xl",
        ".bx--btn--",
        ".bx--btn--disabled",
        ".bx--btn--icon-only",
        ".bx--tooltip__trigger",
        ".bx--tooltip--a11y",
        ".bx--btn--icon-only--",
        ".bx--tooltip--align-",
        ".bx--btn--selected",
        ".bx--skeleton",
        ".bx--pagination-nav__page",
        ".bx--pagination-nav__page--active",
        ".bx--pagination-nav__select",
        ".bx--pagination-nav__page--select",
        ".bx--pagination-nav__select-icon-wrapper",
        ".bx--pagination-nav__select-icon",
      ],
    },
    PaginationSkeleton: {
      path: "carbon-components-svelte/src/Pagination/PaginationSkeleton.svelte",
      classes: [
        ".bx--pagination",
        ".bx--skeleton",
        ".bx--pagination__left",
        ".bx--pagination__right",
        ".bx--pagination--inline",
        ".bx--skeleton__text",
        ".bx--skeleton__heading",
      ],
    },
    PasswordInput: {
      path: "carbon-components-svelte/src/TextInput/PasswordInput.svelte",
      classes: [
        ".bx--form-item",
        ".bx--text-input-wrapper",
        ".bx--password-input-wrapper",
        ".bx--text-input-wrapper--light",
        ".bx--text-input-wrapper--inline",
        ".bx--label",
        ".bx--visually-hidden",
        ".bx--label--disabled",
        ".bx--label--inline",
        ".bx--label--inline--sm",
        ".bx--label--inline--xl",
        ".bx--form__helper-text",
        ".bx--form__helper-text--disabled",
        ".bx--form__helper-text--inline",
        ".bx--text-input__field-outer-wrapper",
        ".bx--text-input__field-outer-wrapper--inline",
        ".bx--text-input__field-wrapper",
        ".bx--text-input__field-wrapper--warning",
        ".bx--text-input__invalid-icon",
        ".bx--text-input__invalid-icon--warning",
        ".bx--text-input",
        ".bx--password-input",
        ".bx--text-input--light",
        ".bx--text-input--invalid",
        ".bx--text-input--warning",
        ".bx--text-input--sm",
        ".bx--text-input--xl",
        ".bx--text-input__divider",
        ".bx--form-requirement",
        ".bx--text-input--password__visibility__toggle",
        ".bx--btn",
        ".bx--btn--icon-only",
        ".bx--btn--disabled",
        ".bx--tooltip__trigger",
        ".bx--tooltip--a11y",
        ".bx--tooltip--top",
        ".bx--tooltip--right",
        ".bx--tooltip--bottom",
        ".bx--tooltip--left",
        ".bx--tooltip--align-start",
        ".bx--tooltip--align-center",
        ".bx--tooltip--align-end",
        ".bx--assistive-text",
        ".bx--icon-visibility-off",
        ".bx--icon-visibility-on",
      ],
    },
    Popover: {
      path: "carbon-components-svelte/src/Popover/Popover.svelte",
      classes: [
        ".bx--popover",
        ".bx--popover--caret",
        ".bx--popover--light",
        ".bx--popover--high-contrast",
        ".bx--popover--top",
        ".bx--popover--top-left",
        ".bx--popover--top-right",
        ".bx--popover--bottom",
        ".bx--popover--bottom-left",
        ".bx--popover--bottom-right",
        ".bx--popover--left",
        ".bx--popover--left-bottom",
        ".bx--popover--left-top",
        ".bx--popover--right",
        ".bx--popover--right-bottom",
        ".bx--popover--right-top",
        ".bx--popover--open",
        ".bx--popover--relative",
        ".bx--popover-contents",
      ],
    },
    ProgressBar: {
      path: "carbon-components-svelte/src/ProgressBar/ProgressBar.svelte",
      classes: [
        ".bx--progress-bar",
        ".bx--progress-bar--indeterminate",
        ".bx--progress-bar--big",
        ".bx--progress-bar--small",
        ".bx--progress-bar--inline",
        ".bx--progress-bar--indented",
        ".bx--progress-bar--error",
        ".bx--progress-bar--finished",
        ".bx--progress-bar__label",
        ".bx--visually-hidden",
        ".bx--progress-bar__status-icon",
        ".bx--progress-bar__track",
        ".bx--progress-bar__bar",
        ".bx--progress-bar__helper-text",
      ],
    },
    ProgressIndicator: {
      path: "carbon-components-svelte/src/ProgressIndicator/ProgressIndicator.svelte",
      classes: [
        ".bx--progress",
        ".bx--progress--vertical",
        ".bx--progress--space-equal",
      ],
    },
    ProgressIndicatorSkeleton: {
      path: "carbon-components-svelte/src/ProgressIndicator/ProgressIndicatorSkeleton.svelte",
      classes: [
        ".bx--progress",
        ".bx--progress--vertical",
        ".bx--skeleton",
        ".bx--progress-step",
        ".bx--progress-step--incomplete",
        ".bx--progress-step-button",
        ".bx--progress-step-button--unclickable",
        ".bx--progress-label",
        ".bx--progress-line",
      ],
    },
    ProgressStep: {
      path: "carbon-components-svelte/src/ProgressIndicator/ProgressStep.svelte",
      classes: [
        ".bx--progress-step",
        ".bx--progress-step--current",
        ".bx--progress-step--complete",
        ".bx--progress-step--incomplete",
        ".bx--progress-step--disabled",
        ".bx--progress-step-button",
        ".bx--progress-step-button--unclickable",
        ".bx--progress__warning",
        ".bx--progress-text",
        ".bx--progress-label",
        ".bx--progress-optional",
        ".bx--progress-line",
      ],
    },
    RadioButton: {
      path: "carbon-components-svelte/src/RadioButton/RadioButton.svelte",
      classes: [
        ".bx--radio-button-wrapper",
        ".bx--radio-button-wrapper--label-left",
        ".bx--radio-button",
        ".bx--radio-button__label",
        ".bx--radio-button__appearance",
        ".bx--visually-hidden",
      ],
    },
    RadioButtonGroup: {
      path: "carbon-components-svelte/src/RadioButtonGroup/RadioButtonGroup.svelte",
      classes: [
        ".bx--form-item",
        ".bx--radio-button-group",
        ".bx--radio-button-group--vertical",
        ".bx--radio-button-group--label-left",
        ".bx--radio-button-group--label-right",
        ".bx--label",
        ".bx--visually-hidden",
        ".bx--form__helper-text",
        ".bx--form__helper-text--disabled",
      ],
    },
    RadioButtonSkeleton: {
      path: "carbon-components-svelte/src/RadioButton/RadioButtonSkeleton.svelte",
      classes: [
        ".bx--radio-button-wrapper",
        ".bx--radio-button",
        ".bx--skeleton",
        ".bx--radio-button__label",
      ],
    },
    RadioTile: {
      path: "carbon-components-svelte/src/Tile/RadioTile.svelte",
      classes: [
        ".bx--tile-input",
        ".bx--tile",
        ".bx--tile--selectable",
        ".bx--tile--is-selected",
        ".bx--tile--light",
        ".bx--tile--disabled",
        ".bx--tile__checkmark",
        ".bx--tile-content",
      ],
    },
    RecursiveList: {
      path: "carbon-components-svelte/src/RecursiveList/RecursiveList.svelte",
      classes: [".bx--link"],
    },
    Row: {
      path: "carbon-components-svelte/src/Grid/Row.svelte",
      classes: [
        ".bx--row",
        ".bx--row--condensed",
        ".bx--row--narrow",
        ".bx--no-gutter",
        ".bx--no-gutter--left",
        ".bx--no-gutter--right",
        ".bx--row-padding",
      ],
    },
    Search: {
      path: "carbon-components-svelte/src/Search/Search.svelte",
      classes: [
        ".bx--search",
        ".bx--search--light",
        ".bx--search--disabled",
        ".bx--search--sm",
        ".bx--search--lg",
        ".bx--search--xl",
        ".bx--search--expandable",
        ".bx--search--expanded",
        ".bx--search-magnifier",
        ".bx--search-magnifier-icon",
        ".bx--label",
        ".bx--search-input",
        ".bx--search-close",
        ".bx--search-close--hidden",
        ".bx--skeleton",
      ],
    },
    SearchSkeleton: {
      path: "carbon-components-svelte/src/Search/SearchSkeleton.svelte",
      classes: [
        ".bx--skeleton",
        ".bx--search--sm",
        ".bx--search--lg",
        ".bx--search--xl",
        ".bx--label",
        ".bx--search-input",
      ],
    },
    Select: {
      path: "carbon-components-svelte/src/Select/Select.svelte",
      classes: [
        ".bx--form-item",
        ".bx--select",
        ".bx--select--inline",
        ".bx--select--light",
        ".bx--select--invalid",
        ".bx--select--disabled",
        ".bx--select--warning",
        ".bx--label",
        ".bx--visually-hidden",
        ".bx--label--disabled",
        ".bx--select-input--inline__wrapper",
        ".bx--select-input__wrapper",
        ".bx--select-input",
        ".bx--select-input--sm",
        ".bx--select-input--xl",
        ".bx--select__arrow",
        ".bx--select__invalid-icon",
        ".bx--form-requirement",
        ".bx--form__helper-text",
        ".bx--form__helper-text--disabled",
        ".bx--select__invalid-icon--warning",
      ],
    },
    SelectableTile: {
      path: "carbon-components-svelte/src/Tile/SelectableTile.svelte",
      classes: [
        ".bx--tile-input",
        ".bx--tile",
        ".bx--tile--selectable",
        ".bx--tile--is-selected",
        ".bx--tile--light",
        ".bx--tile--disabled",
        ".bx--tile__checkmark",
        ".bx--tile-content",
      ],
    },
    SelectableTileGroup: {
      path: "carbon-components-svelte/src/Tile/SelectableTileGroup.svelte",
      classes: [".bx--tile-group", ".bx--label"],
    },
    SelectItem: {
      path: "carbon-components-svelte/src/Select/SelectItem.svelte",
      classes: [".bx--select-option"],
    },
    SelectItemGroup: {
      path: "carbon-components-svelte/src/Select/SelectItemGroup.svelte",
      classes: [".bx--select-optgroup"],
    },
    SelectSkeleton: {
      path: "carbon-components-svelte/src/Select/SelectSkeleton.svelte",
      classes: [
        ".bx--form-item",
        ".bx--label",
        ".bx--skeleton",
        ".bx--select",
        ".bx--select-input",
      ],
    },
    SideNav: {
      path: "carbon-components-svelte/src/UIShell/SideNav.svelte",
      classes: [
        ".bx--side-nav__overlay",
        ".bx--side-nav__overlay-active",
        ".bx--side-nav__navigation",
        ".bx--side-nav",
        ".bx--side-nav--ux",
        ".bx--side-nav--expanded",
        ".bx--side-nav--collapsed",
        ".bx--side-nav--rail",
      ],
    },
    SideNavDivider: {
      path: "carbon-components-svelte/src/UIShell/SideNavDivider.svelte",
      classes: [".bx--side-nav__divider"],
    },
    SideNavItems: {
      path: "carbon-components-svelte/src/UIShell/SideNavItems.svelte",
      classes: [".bx--side-nav__items"],
    },
    SideNavLink: {
      path: "carbon-components-svelte/src/UIShell/SideNavLink.svelte",
      classes: [
        ".bx--side-nav__item",
        ".bx--side-nav__link",
        ".bx--side-nav__link--current",
        ".bx--side-nav__icon",
        ".bx--side-nav__icon--small",
        ".bx--side-nav__link-text",
      ],
    },
    SideNavMenu: {
      path: "carbon-components-svelte/src/UIShell/SideNavMenu.svelte",
      classes: [
        ".bx--side-nav__item",
        ".bx--side-nav__item--icon",
        ".bx--side-nav__submenu",
        ".bx--side-nav__icon",
        ".bx--side-nav__submenu-title",
        ".bx--side-nav__icon--small",
        ".bx--side-nav__submenu-chevron",
        ".bx--side-nav__menu",
      ],
    },
    SideNavMenuItem: {
      path: "carbon-components-svelte/src/UIShell/SideNavMenuItem.svelte",
      classes: [
        ".bx--side-nav__menu-item",
        ".bx--side-nav__link",
        ".bx--side-nav__link-text",
      ],
    },
    SkeletonPlaceholder: {
      path: "carbon-components-svelte/src/SkeletonPlaceholder/SkeletonPlaceholder.svelte",
      classes: [".bx--skeleton__placeholder"],
    },
    SkeletonText: {
      path: "carbon-components-svelte/src/SkeletonText/SkeletonText.svelte",
      classes: [".bx--skeleton__text", ".bx--skeleton__heading"],
    },
    SkipToContent: {
      path: "carbon-components-svelte/src/UIShell/SkipToContent.svelte",
      classes: [".bx--skip-to-content"],
    },
    Slider: {
      path: "carbon-components-svelte/src/Slider/Slider.svelte",
      classes: [
        ".bx--form-item",
        ".bx--label",
        ".bx--label--disabled",
        ".bx--visually-hidden",
        ".bx--slider-container",
        ".bx--slider__range-label",
        ".bx--slider",
        ".bx--slider--disabled",
        ".bx--slider__thumb",
        ".bx--slider__track",
        ".bx--slider__filled-track",
        ".bx--text-input",
        ".bx--slider-text-input",
        ".bx--text-input--light",
        ".bx--text-input--invalid",
      ],
    },
    SliderSkeleton: {
      path: "carbon-components-svelte/src/Slider/SliderSkeleton.svelte",
      classes: [
        ".bx--form-item",
        ".bx--label",
        ".bx--skeleton",
        ".bx--slider-container",
        ".bx--slider__range-label",
        ".bx--slider",
        ".bx--slider__track",
        ".bx--slider__filled-track",
        ".bx--slider__thumb",
      ],
    },
    Stack: {
      path: "carbon-components-svelte/src/Stack/Stack.svelte",
      classes: [
        ".bx--stack",
        ".bx--stack-vertical",
        ".bx--stack-horizontal",
        ".bx--stack-scale-1",
        ".bx--stack-scale-2",
        ".bx--stack-scale-3",
        ".bx--stack-scale-4",
        ".bx--stack-scale-5",
        ".bx--stack-scale-6",
        ".bx--stack-scale-7",
        ".bx--stack-scale-8",
        ".bx--stack-scale-9",
        ".bx--stack-scale-10",
        ".bx--stack-scale-11",
        ".bx--stack-scale-12",
        ".bx--stack-scale-13",
      ],
    },
    StructuredList: {
      path: "carbon-components-svelte/src/StructuredList/StructuredList.svelte",
      classes: [
        ".bx--structured-list",
        ".bx--structured-list--selection",
        ".bx--structured-list--condensed",
        ".bx--structured-list--flush",
      ],
    },
    StructuredListBody: {
      path: "carbon-components-svelte/src/StructuredList/StructuredListBody.svelte",
      classes: [".bx--structured-list-tbody"],
    },
    StructuredListCell: {
      path: "carbon-components-svelte/src/StructuredList/StructuredListCell.svelte",
      classes: [
        ".bx--structured-list-th",
        ".bx--structured-list-td",
        ".bx--structured-list-content--nowrap",
      ],
    },
    StructuredListHead: {
      path: "carbon-components-svelte/src/StructuredList/StructuredListHead.svelte",
      classes: [".bx--structured-list-thead"],
    },
    StructuredListInput: {
      path: "carbon-components-svelte/src/StructuredList/StructuredListInput.svelte",
      classes: [".bx--structured-list-input"],
    },
    StructuredListRow: {
      path: "carbon-components-svelte/src/StructuredList/StructuredListRow.svelte",
      classes: [
        ".bx--structured-list-row",
        ".bx--structured-list-row--header-row",
      ],
    },
    StructuredListSkeleton: {
      path: "carbon-components-svelte/src/StructuredList/StructuredListSkeleton.svelte",
      classes: [
        ".bx--skeleton",
        ".bx--structured-list",
        ".bx--structured-list-thead",
        ".bx--structured-list-row",
        ".bx--structured-list-row--header-row",
        ".bx--structured-list-th",
        ".bx--structured-list-tbody",
        ".bx--structured-list-td",
      ],
    },
    Switch: {
      path: "carbon-components-svelte/src/ContentSwitcher/Switch.svelte",
      classes: [
        ".bx--content-switcher-btn",
        ".bx--content-switcher--selected",
        ".bx--content-switcher__label",
      ],
    },
    Tab: {
      path: "carbon-components-svelte/src/Tabs/Tab.svelte",
      classes: [
        ".bx--tabs__nav-item",
        ".bx--tabs__nav-item--disabled",
        ".bx--tabs__nav-item--selected",
        ".bx--tabs__nav-link",
      ],
    },
    TabContent: {
      path: "carbon-components-svelte/src/Tabs/TabContent.svelte",
      classes: [".bx--tab-content"],
    },
    Table: {
      path: "carbon-components-svelte/src/DataTable/Table.svelte",
      classes: [
        ".bx--data-table_inner-container",
        ".bx--data-table",
        ".bx--data-table--compact",
        ".bx--data-table--short",
        ".bx--data-table--tall",
        ".bx--data-table--md",
        ".bx--data-table--sort",
        ".bx--data-table--zebra",
        ".bx--data-table--static",
        ".bx--data-table--sticky-header",
      ],
    },
    TableBody: {
      path: "carbon-components-svelte/src/DataTable/TableBody.svelte",
      classes: [],
    },
    TableCell: {
      path: "carbon-components-svelte/src/DataTable/TableCell.svelte",
      classes: [],
    },
    TableContainer: {
      path: "carbon-components-svelte/src/DataTable/TableContainer.svelte",
      classes: [
        ".bx--data-table-container",
        ".bx--data-table-container--static",
        ".bx--data-table--max-width",
        ".bx--data-table-header",
        ".bx--data-table-header__title",
        ".bx--data-table-header__description",
      ],
    },
    TableHead: {
      path: "carbon-components-svelte/src/DataTable/TableHead.svelte",
      classes: [],
    },
    TableHeader: {
      path: "carbon-components-svelte/src/DataTable/TableHeader.svelte",
      classes: [
        ".bx--table-sort",
        ".bx--table-sort--active",
        ".bx--table-sort--ascending",
        ".bx--table-header-label",
        ".bx--table-sort__icon",
        ".bx--table-sort__icon-unsorted",
      ],
    },
    TableRow: {
      path: "carbon-components-svelte/src/DataTable/TableRow.svelte",
      classes: [],
    },
    Tabs: {
      path: "carbon-components-svelte/src/Tabs/Tabs.svelte",
      classes: [
        ".bx--tabs",
        ".bx--tabs--container",
        ".bx--tabs-trigger",
        ".bx--tabs-trigger-text",
        ".bx--tabs__nav",
        ".bx--tabs__nav--hidden",
      ],
    },
    TabsSkeleton: {
      path: "carbon-components-svelte/src/Tabs/TabsSkeleton.svelte",
      classes: [
        ".bx--tabs",
        ".bx--skeleton",
        ".bx--tabs--scrollable",
        ".bx--tabs--scrollable--container",
        ".bx--tabs--scrollable__nav",
        ".bx--tabs--scrollable__nav-item",
        ".bx--tabs__nav-link",
      ],
    },
    Tag: {
      path: "carbon-components-svelte/src/Tag/Tag.svelte",
      classes: [
        ".bx--tag",
        ".bx--tag--disabled",
        ".bx--tag--filter",
        ".bx--tag--sm",
        ".bx--tag--red",
        ".bx--tag--magenta",
        ".bx--tag--purple",
        ".bx--tag--blue",
        ".bx--tag--cyan",
        ".bx--tag--teal",
        ".bx--tag--green",
        ".bx--tag--gray",
        ".bx--tag--cool-gray",
        ".bx--tag--warm-gray",
        ".bx--tag--high-contrast",
        ".bx--tag--outline",
        ".bx--tag__label",
        ".bx--tag__close-icon",
        ".bx--tag--interactive",
        ".bx--tag__custom-icon",
        ".bx--skeleton",
      ],
    },
    TagSkeleton: {
      path: "carbon-components-svelte/src/Tag/TagSkeleton.svelte",
      classes: [".bx--tag", ".bx--tag--sm", ".bx--skeleton"],
    },
    TextArea: {
      path: "carbon-components-svelte/src/TextArea/TextArea.svelte",
      classes: [
        ".bx--form-item",
        ".bx--text-area__label-wrapper",
        ".bx--label",
        ".bx--visually-hidden",
        ".bx--label--disabled",
        ".bx--text-area__wrapper",
        ".bx--text-area__invalid-icon",
        ".bx--text-area__invalid-icon--warning",
        ".bx--text-area",
        ".bx--text-area--light",
        ".bx--text-area--invalid",
        ".bx--text-area--warning",
        ".bx--form__helper-text",
        ".bx--form__helper-text--disabled",
        ".bx--form-requirement",
      ],
    },
    TextAreaSkeleton: {
      path: "carbon-components-svelte/src/TextArea/TextAreaSkeleton.svelte",
      classes: [
        ".bx--form-item",
        ".bx--label",
        ".bx--skeleton",
        ".bx--text-area",
      ],
    },
    TextInput: {
      path: "carbon-components-svelte/src/TextInput/TextInput.svelte",
      classes: [
        ".bx--form-item",
        ".bx--text-input-wrapper",
        ".bx--text-input-wrapper--inline",
        ".bx--text-input-wrapper--light",
        ".bx--text-input-wrapper--readonly",
        ".bx--text-input__label-helper-wrapper",
        ".bx--label",
        ".bx--visually-hidden",
        ".bx--label--disabled",
        ".bx--label--inline",
        ".bx--label--inline--sm",
        ".bx--label--inline--xl",
        ".bx--form__helper-text",
        ".bx--form__helper-text--disabled",
        ".bx--form__helper-text--inline",
        ".bx--label--inline-sm",
        ".bx--label--inline-xl",
        ".bx--text-input__field-outer-wrapper",
        ".bx--text-input__field-outer-wrapper--inline",
        ".bx--text-input__field-wrapper",
        ".bx--text-input__field-wrapper--warning",
        ".bx--text-input__readonly-icon",
        ".bx--text-input__invalid-icon",
        ".bx--text-input__invalid-icon--warning",
        ".bx--text-input",
        ".bx--text-input--light",
        ".bx--text-input--invalid",
        ".bx--text-input--warning",
        ".bx--text-input--sm",
        ".bx--text-input--xl",
        ".bx--text-input__divider",
        ".bx--form-requirement",
      ],
    },
    TextInputSkeleton: {
      path: "carbon-components-svelte/src/TextInput/TextInputSkeleton.svelte",
      classes: [
        ".bx--form-item",
        ".bx--label",
        ".bx--skeleton",
        ".bx--text-input",
      ],
    },
    Theme: {
      path: "carbon-components-svelte/src/Theme/Theme.svelte",
      classes: [
        ".bx--form-item",
        ".bx--toggle-input",
        ".bx--toggle-input--small",
        ".bx--toggle-input__label",
        ".bx--visually-hidden",
        ".bx--toggle__switch",
        ".bx--toggle__text--off",
        ".bx--toggle__text--on",
        ".bx--select",
        ".bx--select--inline",
        ".bx--select--light",
        ".bx--select--invalid",
        ".bx--select--disabled",
        ".bx--select--warning",
        ".bx--label",
        ".bx--label--disabled",
        ".bx--select-input--inline__wrapper",
        ".bx--select-input__wrapper",
        ".bx--select-input",
        ".bx--select-input--sm",
        ".bx--select-input--xl",
        ".bx--select__arrow",
        ".bx--select__invalid-icon",
        ".bx--form-requirement",
        ".bx--form__helper-text",
        ".bx--form__helper-text--disabled",
        ".bx--select__invalid-icon--warning",
        ".bx--select-option",
      ],
    },
    Tile: {
      path: "carbon-components-svelte/src/Tile/Tile.svelte",
      classes: [".bx--tile", ".bx--tile--light"],
    },
    TileGroup: {
      path: "carbon-components-svelte/src/Tile/TileGroup.svelte",
      classes: [".bx--tile-group", ".bx--label"],
    },
    TimePicker: {
      path: "carbon-components-svelte/src/TimePicker/TimePicker.svelte",
      classes: [
        ".bx--form-item",
        ".bx--time-picker",
        ".bx--time-picker--light",
        ".bx--time-picker--invalid",
        ".bx--time-picker--sm",
        ".bx--time-picker--xl",
        ".bx--select--light",
        ".bx--time-picker__input",
        ".bx--label",
        ".bx--visually-hidden",
        ".bx--label--disabled",
        ".bx--time-picker__input-field",
        ".bx--text-input",
        ".bx--text-input--light",
        ".bx--text-input--invalid",
        ".bx--form-requirement",
      ],
    },
    TimePickerSelect: {
      path: "carbon-components-svelte/src/TimePicker/TimePickerSelect.svelte",
      classes: [
        ".bx--select",
        ".bx--time-picker__select",
        ".bx--label",
        ".bx--visually-hidden",
        ".bx--select-input",
        ".bx--select__arrow",
      ],
    },
    ToastNotification: {
      path: "carbon-components-svelte/src/Notification/ToastNotification.svelte",
      classes: [
        ".bx--toast-notification",
        ".bx--toast-notification--low-contrast",
        ".bx--toast-notification--error",
        ".bx--toast-notification--info",
        ".bx--toast-notification--info-square",
        ".bx--toast-notification--success",
        ".bx--toast-notification--warning",
        ".bx--toast-notification--warning-alt",
        ".bx--toast-notification__details",
        ".bx--toast-notification__title",
        ".bx--toast-notification__subtitle",
        ".bx--toast-notification__caption",
        ".bx--toast-notification__icon",
        ".bx--inline-notification__icon",
        ".bx--toast-notification__close-button",
        ".bx--inline-notification__close-button",
        ".bx--toast-notification__close-icon",
        ".bx--inline-notification__close-icon",
      ],
    },
    Toggle: {
      path: "carbon-components-svelte/src/Toggle/Toggle.svelte",
      classes: [
        ".bx--form-item",
        ".bx--toggle-input",
        ".bx--toggle-input--small",
        ".bx--toggle-input__label",
        ".bx--visually-hidden",
        ".bx--toggle__switch",
        ".bx--toggle__text--off",
        ".bx--toggle__text--on",
      ],
    },
    ToggleSkeleton: {
      path: "carbon-components-svelte/src/Toggle/ToggleSkeleton.svelte",
      classes: [
        ".bx--form-item",
        ".bx--toggle",
        ".bx--toggle--small",
        ".bx--skeleton",
        ".bx--toggle__label",
        ".bx--toggle__label-text",
        ".bx--toggle__text--left",
        ".bx--toggle__appearance",
        ".bx--toggle__text--right",
      ],
    },
    toHierarchy: {
      path: "carbon-components-svelte/src/utils/toHierarchy.js",
      classes: [],
    },
    Toolbar: {
      path: "carbon-components-svelte/src/DataTable/Toolbar.svelte",
      classes: [
        ".bx--table-toolbar",
        ".bx--table-toolbar--small",
        ".bx--table-toolbar--normal",
      ],
    },
    ToolbarBatchActions: {
      path: "carbon-components-svelte/src/DataTable/ToolbarBatchActions.svelte",
      classes: [
        ".bx--batch-actions",
        ".bx--batch-actions--active",
        ".bx--batch-summary",
        ".bx--batch-summary__para",
        ".bx--action-list",
        ".bx--batch-summary__cancel",
        ".bx--assistive-text",
        ".bx--btn__icon",
        ".bx--btn",
        ".bx--btn--expressive",
        ".bx--btn--sm",
        ".bx--btn--md",
        ".bx--btn--field",
        ".bx--btn--lg",
        ".bx--btn--xl",
        ".bx--btn--",
        ".bx--btn--disabled",
        ".bx--btn--icon-only",
        ".bx--tooltip__trigger",
        ".bx--tooltip--a11y",
        ".bx--btn--icon-only--",
        ".bx--tooltip--align-",
        ".bx--btn--selected",
      ],
    },
    ToolbarContent: {
      path: "carbon-components-svelte/src/DataTable/ToolbarContent.svelte",
      classes: [".bx--toolbar-content"],
    },
    ToolbarMenu: {
      path: "carbon-components-svelte/src/DataTable/ToolbarMenu.svelte",
      classes: [
        ".bx--toolbar-action",
        ".bx--overflow-menu",
        ".bx--overflow-menu--open",
        ".bx--overflow-menu--light",
        ".bx--overflow-menu--sm",
        ".bx--overflow-menu--xl",
        ".bx--overflow-menu__icon",
        ".bx--overflow-menu-options",
        ".bx--overflow-menu--flip",
        ".bx--overflow-menu-options--open",
        ".bx--overflow-menu-options--light",
        ".bx--overflow-menu-options--sm",
        ".bx--overflow-menu-options--xl",
        ".bx--breadcrumb-menu-options",
      ],
    },
    ToolbarMenuItem: {
      path: "carbon-components-svelte/src/DataTable/ToolbarMenuItem.svelte",
      classes: [
        ".bx--overflow-menu-options__option",
        ".bx--overflow-menu--divider",
        ".bx--overflow-menu-options__option--danger",
        ".bx--overflow-menu-options__option--disabled",
        ".bx--overflow-menu-options__option-content",
        ".bx--overflow-menu-options__btn",
      ],
    },
    ToolbarSearch: {
      path: "carbon-components-svelte/src/DataTable/ToolbarSearch.svelte",
      classes: [
        ".bx--toolbar-search-container-active",
        ".bx--toolbar-search-container-persistent",
        ".bx--toolbar-search-container-expandable",
        ".bx--toolbar-search-container-disabled",
        ".bx--search",
        ".bx--search--light",
        ".bx--search--disabled",
        ".bx--search--sm",
        ".bx--search--lg",
        ".bx--search--xl",
        ".bx--search--expandable",
        ".bx--search--expanded",
        ".bx--search-magnifier",
        ".bx--search-magnifier-icon",
        ".bx--label",
        ".bx--search-input",
        ".bx--search-close",
        ".bx--search-close--hidden",
      ],
    },
    Tooltip: {
      path: "carbon-components-svelte/src/Tooltip/Tooltip.svelte",
      classes: [
        ".bx--tooltip__label",
        ".bx--tooltip",
        ".bx--tooltip--shown",
        ".bx--tooltip--top",
        ".bx--tooltip--right",
        ".bx--tooltip--bottom",
        ".bx--tooltip--left",
        ".bx--tooltip--align-center",
        ".bx--tooltip--align-start",
        ".bx--tooltip--align-end",
        ".bx--tooltip__caret",
        ".bx--tooltip__content",
        ".bx--tooltip__trigger",
      ],
    },
    TooltipDefinition: {
      path: "carbon-components-svelte/src/TooltipDefinition/TooltipDefinition.svelte",
      classes: [
        ".bx--tooltip--definition",
        ".bx--tooltip--a11y",
        ".bx--tooltip__trigger",
        ".bx--tooltip__trigger--definition",
        ".bx--tooltip--hidden",
        ".bx--tooltip--visible",
        ".bx--tooltip--top",
        ".bx--tooltip--bottom",
        ".bx--tooltip--align-start",
        ".bx--tooltip--align-center",
        ".bx--tooltip--align-end",
        ".bx--assistive-text",
      ],
    },
    TooltipFooter: {
      path: "carbon-components-svelte/src/Tooltip/TooltipFooter.svelte",
      classes: [".bx--tooltip__footer"],
    },
    TooltipIcon: {
      path: "carbon-components-svelte/src/TooltipIcon/TooltipIcon.svelte",
      classes: [
        ".bx--tooltip__trigger",
        ".bx--tooltip--a11y",
        ".bx--tooltip--hidden",
        ".bx--tooltip--top",
        ".bx--tooltip--right",
        ".bx--tooltip--bottom",
        ".bx--tooltip--left",
        ".bx--tooltip--align-start",
        ".bx--tooltip--align-center",
        ".bx--tooltip--align-end",
        ".bx--assistive-text",
      ],
    },
    TreeView: {
      path: "carbon-components-svelte/src/TreeView/TreeView.svelte",
      classes: [
        ".bx--label",
        ".bx--tree",
        ".bx--tree--default",
        ".bx--tree--compact",
        ".li.bx--tree-node:not(.bx--tree-node--disabled)",
        ".bx--tree-node--disabled",
        ".li.bx--tree-node",
        ".bx--tree-node",
        ".bx--tree-parent-node",
        ".bx--tree-node--active",
        ".bx--tree-node--selected",
        ".bx--tree-node--with-icon",
        ".bx--tree-node__label",
        ".bx--tree-parent-node__toggle",
        ".bx--tree-parent-node__toggle-icon",
        ".bx--tree-parent-node__toggle-icon--expanded",
        ".bx--tree-node__label__details",
        ".bx--tree-node__icon",
        ".bx--tree-node__children",
      ],
    },
    truncate: {
      path: "carbon-components-svelte/src/Truncate/truncate.js",
      classes: [],
    },
    Truncate: {
      path: "carbon-components-svelte/src/Truncate/Truncate.svelte",
      classes: [".bx--text-truncate--end", ".bx--text-truncate--front"],
    },
    UnorderedList: {
      path: "carbon-components-svelte/src/UnorderedList/UnorderedList.svelte",
      classes: [
        ".bx--list--unordered",
        ".bx--list--nested",
        ".bx--list--expressive",
      ],
    },
  });
